### ISSUE TITLE
SqlReturn uses incorrect value

### ISSUE THREAD

**Issue by Sineaggi** [pacman82/odbc-sys#31] opened 2021-02-12 03:42 UTC
In pr #27 SqlReturn changed
```    SQL_INVALID_HANDLE = -2,```
to     ```pub const INVALID_HANDLE: SqlReturn = SqlReturn(-1);```

Is this correct?

**Comment by pacman82** [comment] 2021-02-12 10:13
Thanks for politely phrasing it as a question, but no this is an accidental change. I screwed up. The downstream libraries pretty much prevent INVALID HANDLES by design, how on earth did you find this? Luckily it should not be to hard to write a test for this to prevent that error in the future.

**Comment by pacman82** [comment] 2021-02-12 11:51
Fixed in 0.17.1. Thanks for reporting!

**Closed by pacman82** 2021-02-12 11:51 UTC
Labels: bug
